# Site settings
title: Sumit Gupta
email: sumit(at)apache(dot)org
description: > # this means to ignore newlines until "baseurl:"
  Knox tips and tricks
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://sumitg.githib.io" # the base hostname & protocol for your site
future: false
twitter_username: sgfraggle
github_username:  sumitg

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["smart", "tables", "no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data"]

#markdown: kramdown
#kramdown:
#  input: GFM